### PR TITLE
Dashboard redesign

### PR DESCRIPTION
**Pull request by NealSun96**
@marouane97 

My ideas for this redesign:
1. Collapse button to hide the list of 4 assignments seems necessary, what do u think?
2. For the text colors, should we, instead of green, red, and black, just do black or gray? I think black or gray looks more slick and go well with ur new icons, what do you think?
3. Auto hide the ">" icon? Makes sense to me

Let me know about the time estimation for point 1. If it's too long let's postpone this

### CODE REVIEW

**Comment by marouane97** [comment]
1. black and gray seem fine if we're disabling access to complete assignments, otherwise, I think it'll be confusing for users.
2. ill try to add a collapsible menu asap, tho I don't feel like it's necessary.
3. I feel like we should use different icons for each of the assignments, something that makes sense. ill try to add some later

**Comment by NealSun96** [comment]
@marouane97 So yeah, we will disable the buttons like the old courseOne.

The thing about collapsible is that, I fear when there are too many courses, it gets too clunky. What do you think? The bars look pretty long to me.

**Comment by NealSun96** [comment]
@marouane97 Is this one finished yet?

**Comment by marouane97** [comment]
@NealSun96 you can close this since I moved everything from this to the new branch.

**Pull request closed without merging**
